name: Build & Commit PDF

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Utilise LuaLaTeX (gère mieux l’UTF-8 que pdflatex)
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          # si tu veux rester en pdfLaTeX: commente la ligne ci-dessus et ajoute \usepackage[utf8]{inputenc} dans ton .tex

      - name: Commit main.pdf back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: update main.pdf"
          file_pattern: main.pdf
